pipeline {
    agent any
    stages {
         stage('Complete1') {
            steps {
                echo "Complete"
            }
        }
         stage('Complete') {
            steps {
                echo "Complete"
            }
        }
    }
}
