pipeline {
    agent any
    stages {
         stage('Complete1') {
            steps {
                echo "Complete"
            }
        }
         stage('Complete') {
            steps {
                echo "Complete"
            }
        }
        stage('Complete2') {
            steps {
                echo "Complete Yusuf"
            }
        }
         stage('Complete3') {
            steps {
                echo "Complete Yusuf3"
            }
        }
        stage('Finished') {
            steps {
                echo "Finished"
            }
        }
    }
}
